export const INTEGRATION_TARGET_REPOSITORY = Symbol("INTEGRATION_TARGET_REPOSITORY");
export const INTEGRATION_TARGET_FEATURE_GATE_POLICY = Symbol(
  "INTEGRATION_TARGET_FEATURE_GATE_POLICY",
);
export const INTEGRATION_TARGET_SETTINGS = Symbol("INTEGRATION_TARGET_SETTINGS");
export const INTEGRATION_TARGET_AUDIT_LOG = Symbol("INTEGRATION_TARGET_AUDIT_LOG");
