export {
  canonicalHostedActualOwnerCapabilityAttestationBytes,
  canonicalHostedActualOwnerCapabilityAttestationUnsignedBytes,
  hostedActualOwnerCapabilityAttestationSigningBytes,
  HostedActualOwnerCapabilityAttestationValidationError,
  parseHostedActualOwnerCapabilityAttestation,
  validateHostedActualOwnerCapabilityAttestationSubject,
  validateHostedActualOwnerCapabilityAttestationUnsigned,
} from './attestationCodec';
