import {
  type AbsenceRow,
  type ApiSurface,
  REVIEWED_CONTROL_FILES,
  type SemanticRow,
} from './parity-scan-contracts';

export const apiGroups: Array<{
  surface: ApiSurface;
  owner: string;
  namespace: string;
  disposition: SemanticRow['disposition'];
  securityClass: string;
  target: string;
  members: string[];
}> = [
  {
    surface: 'TeamsAPI',
    owner: 'team-lifecycle',
    namespace: 'team.lifecycle',
    disposition: 'decomposed',
    securityClass: 'team-resource',
    target: 'WP-7-TEAM-LIFECYCLE',
    members: [
      'list',
      'getData',
      'deleteTeam',
      'restoreTeam',
      'permanentlyDeleteTeam',
      'deleteDraft',
      'prepareProvisioning',
      'createTeam',
      'getProvisioningStatus',
      'getLaunchFailureDiagnostics',
      'cancelProvisioning',
      'stop',
      'createConfig',
      'launchTeam',
      'updateConfig',
      'addMember',
      'replaceMembers',
      'removeMember',
      'restoreMember',
      'updateMemberRole',
      'getMemberSpawnStatuses',
      'restartMember',
      'skipMemberForLaunch',
    ],
  },
  {
    surface: 'TeamsAPI',
    owner: 'workspace-registry',
    namespace: 'workspace.registry',
    disposition: 'decomposed',
    securityClass: 'workspace-authorization',
    target: 'WP-3-WORKSPACE-REGISTRY',
    members: [
      'getWorktreeGitStatus',
      'initializeGitRepository',
      'createInitialGitCommit',
      'getProjectBranch',
      'setProjectBranchTracking',
      'onProjectBranchChange',
    ],
  },
  {
    surface: 'TeamsAPI',
    owner: 'team-task-board',
    namespace: 'team.task',
    disposition: 'decomposed',
    securityClass: 'team-resource',
    target: 'WP-8-TASK-BOARD',
    members: [
      'getTaskChangePresence',
      'setChangePresenceTracking',
      'createTask',
      'getTask',
      'requestReview',
      'updateKanban',
      'updateKanbanColumnOrder',
      'updateTaskStatus',
      'updateTaskOwner',
      'updateTaskFields',
      'startTask',
      'startTaskByUser',
      'getAllTasks',
      'addTaskComment',
      'setTaskClarification',
      'softDeleteTask',
      'restoreTask',
      'getDeletedTasks',
      'addTaskRelationship',
      'removeTaskRelationship',
    ],
  },
  {
    surface: 'TeamsAPI',
    owner: 'team-messaging',
    namespace: 'team.message',
    disposition: 'decomposed',
    securityClass: 'team-resource',
    target: 'WP-8-MESSAGING',
    members: [
      'getSavedRequest',
      'sendMessage',
      'getOpenCodeRuntimeDeliveryStatus',
      'getMessagesPage',
      'processSend',
    ],
  },
  {
    surface: 'TeamsAPI',
    owner: 'team-runtime-control',
    namespace: 'team.runtime',
    disposition: 'decomposed',
    securityClass: 'runtime-operator',
    target: 'WP-5-RUNTIME-CONTROL',
    members: [
      'setToolActivityTracking',
      'setTaskLogStreamTracking',
      'getClaudeLogs',
      'getMemberActivityMeta',
      'processAlive',
      'aliveList',
      'getMemberLogs',
      'getLogsForTask',
      'getTaskActivity',
      'getTaskActivityDetail',
      'getTaskLogStreamSummary',
      'getTaskLogStream',
      'getTaskExactLogSummaries',
      'getTaskExactLogDetail',
      'getMemberStats',
      'killProcess',
      'getLeadActivity',
      'getLeadContext',
      'getTeamAgentRuntime',
      'retryFailedOpenCodeSecondaryLanes',
    ],
  },
  {
    surface: 'TeamsAPI',
    owner: 'agent-attachments',
    namespace: 'agent.attachment',
    disposition: 'decomposed',
    securityClass: 'bounded-content',
    target: 'WP-9-ATTACHMENTS',
    members: ['getAttachments', 'saveTaskAttachment', 'getTaskAttachment', 'deleteTaskAttachment'],
  },
  {
    surface: 'TeamsAPI',
    owner: 'team-approvals',
    namespace: 'team.approval',
    disposition: 'decomposed',
    securityClass: 'approval-policy',
    target: 'WP-9-APPROVALS',
    members: [
      'respondToToolApproval',
      'validateCliArgs',
      'onToolApprovalEvent',
      'updateToolApprovalSettings',
      'readFileForToolApproval',
    ],
  },
  {
    surface: 'TeamsAPI',
    owner: 'team-console',
    namespace: 'team.console',
    disposition: 'direct',
    securityClass: 'renderer-local',
    target: 'WP-7-TEAM-CONSOLE',
    members: ['showMessageNotification', 'onTeamChange', 'onProvisioningProgress'],
  },
  {
    surface: 'ReviewAPI',
    owner: 'team-review',
    namespace: 'team.review',
    disposition: 'decomposed',
    securityClass: 'review-change-set',
    target: 'WP-9-REVIEW',
    members: [
      'getAgentChanges',
      'getTaskChanges',
      'getTeamTaskChangeSummaries',
      'invalidateTaskChangeSummaries',
      'getChangeStats',
      'getFileContent',
      'applyDecisions',
      'executeMutation',
      'retryMutationRecovery',
      'restoreHistory',
      'checkConflict',
      'rejectHunks',
      'rejectFile',
      'previewReject',
      'saveEditedFile',
      'deleteEditedFile',
      'restoreRejectedRename',
      'reapplyRejectedRename',
      'watchFiles',
      'unwatchFiles',
      'onExternalFileChange',
      'loadDecisions',
      'saveDecisions',
      'clearDecisions',
      'loadDecisionConflictCandidates',
      'resolveDecisionConflictCandidate',
      'loadDraftHistory',
      'saveDraftHistoryEntry',
      'clearDraftHistory',
      'loadDraftHistoryConflictCandidates',
      'resolveDraftHistoryConflictCandidate',
      'replaceDraftHistoryConflictCandidate',
    ],
  },
  {
    surface: 'ReviewAPI',
    owner: 'team-review',
    namespace: 'team.review',
    disposition: 'desktop-only',
    securityClass: 'desktop-shell',
    target: 'DEFERRED-DESKTOP-ONLY',
    members: ['onCmdN', 'getGitFileLog'],
  },
  {
    surface: 'CrossTeamAPI',
    owner: 'team-messaging',
    namespace: 'team.message.cross-team',
    disposition: 'decomposed',
    securityClass: 'cross-team-resource',
    target: 'WP-8-MESSAGING',
    members: ['send', 'listTargets', 'getOutbox'],
  },
];

// These are reviewed semantic assignments. Source hashes are refreshable evidence, never identity.
export const actionSeeds: Array<
  Omit<SemanticRow, 'sourceRefs'> & {
    refs: Array<[keyof typeof REVIEWED_CONTROL_FILES, string]>;
  }
> = [
  {
    id: 'team.console.select',
    owner: 'team-console',
    disposition: 'direct',
    securityClass: 'team-read',
    target: 'WP-7-TEAM-CONSOLE',
    evidence: ['keyboard/click equivalence', 'selection generation'],
    refs: [
      ['list', '7ae3e9868fb0d4a2'],
      ['list', '3d61968c3b27192f'],
      ['create', 'a41ca0eb05d0e44d'],
    ],
  },
  {
    id: 'team.lifecycle.launch',
    owner: 'team-lifecycle',
    disposition: 'decomposed',
    securityClass: 'team-operator',
    target: 'WP-7-TEAM-LIFECYCLE',
    evidence: ['idempotent accepted run', 'runtime outcome'],
    refs: [
      ['list', '6316b98384b52106'],
      ['detail', '57315f4848354f04'],
      ['detail', 'b0f60eaa09e35acc'],
    ],
  },
  {
    id: 'team.lifecycle.stop',
    owner: 'team-lifecycle',
    disposition: 'decomposed',
    securityClass: 'team-operator',
    target: 'WP-7-TEAM-LIFECYCLE',
    evidence: ['lifecycle generation', 'runtime stop outcome'],
    refs: [
      ['list', '9e5a0346eee1dc22'],
      ['detail', 'f24d2defb60f97d3'],
    ],
  },
  {
    id: 'team.lifecycle.copy-draft',
    owner: 'team-lifecycle',
    disposition: 'decomposed',
    securityClass: 'team-mutation',
    target: 'WP-7-TEAM-LIFECYCLE',
    evidence: ['new stable team identity'],
    refs: [['list', 'caca7b02e0fe8e0c']],
  },
  {
    id: 'team.lifecycle.delete',
    owner: 'team-lifecycle',
    disposition: 'decomposed',
    securityClass: 'destructive-team-operator',
    target: 'WP-7-TEAM-LIFECYCLE',
    evidence: ['tombstone generation', 'partial cleanup outcome'],
    refs: [
      ['list', '31aff054fdea44fc'],
      ['detail', '7d3361a6fdf74099'],
      ['detail', 'b8f7b322927174be'],
    ],
  },
  {
    id: 'team.lifecycle.restore',
    owner: 'team-lifecycle',
    disposition: 'decomposed',
    securityClass: 'team-operator',
    target: 'WP-7-TEAM-LIFECYCLE',
    evidence: ['tombstone generation check'],
    refs: [['list', '4aed9e873872f4c9']],
  },
  {
    id: 'team.lifecycle.permanently-delete',
    owner: 'team-lifecycle',
    disposition: 'decomposed',
    securityClass: 'destructive-team-operator',
    target: 'WP-7-TEAM-LIFECYCLE',
    evidence: ['explicit irreversible confirmation'],
    refs: [['list', 'f94e171aad27f966']],
  },
  {
    id: 'team.lifecycle.list.refresh',
    owner: 'team-lifecycle',
    disposition: 'direct',
    securityClass: 'team-read',
    target: 'WP-7-TEAM-LIFECYCLE',
    evidence: ['bounded freshness generation'],
    refs: [['list', 'e51dbba28734b4f3']],
  },
  {
    id: 'team.lifecycle.create-draft',
    owner: 'team-lifecycle',
    disposition: 'decomposed',
    securityClass: 'team-mutation',
    target: 'WP-7-TEAM-LIFECYCLE',
    evidence: ['draft identity before provisioning'],
    refs: [
      ['list', '51e06c68cf47389f'],
      ['create', '4fb257c290cbb747'],
    ],
  },
  {
    id: 'team.lifecycle.delete-draft',
    owner: 'team-lifecycle',
    disposition: 'decomposed',
    securityClass: 'destructive-team-operator',
    target: 'WP-7-TEAM-LIFECYCLE',
    evidence: ['draft-only deletion'],
    refs: [['detail', '1524fdc2302874a8']],
  },
  {
    id: 'team.lifecycle.edit-config',
    owner: 'team-lifecycle',
    disposition: 'decomposed',
    securityClass: 'team-mutation',
    target: 'WP-7-TEAM-LIFECYCLE',
    evidence: ['config revision conflict'],
    refs: [['detail', 'f5174a77b50a0515']],
  },
  {
    id: 'team.lifecycle.add-member',
    owner: 'team-lifecycle',
    disposition: 'decomposed',
    securityClass: 'team-mutation',
    target: 'WP-7-TEAM-LIFECYCLE',
    evidence: ['roster generation'],
    refs: [['detail', '2822e8d54b308717']],
  },
  {
    id: 'team.lifecycle.remove-member',
    owner: 'team-lifecycle',
    disposition: 'decomposed',
    securityClass: 'destructive-team-operator',
    target: 'WP-7-TEAM-LIFECYCLE',
    evidence: ['roster generation and runtime outcome'],
    refs: [['detail', 'e39a599d1bf8f481']],
  },
  {
    id: 'team.task.create',
    owner: 'team-task-board',
    disposition: 'decomposed',
    securityClass: 'team-mutation',
    target: 'WP-8-TASK-BOARD',
    evidence: ['task revision and delivery outcome'],
    refs: [
      ['detail', 'f6be75adbc83db1b'],
      ['detail', 'f2ce29562f9b62f6'],
    ],
  },
  {
    id: 'team.task.request-changes',
    owner: 'team-task-board',
    disposition: 'decomposed',
    securityClass: 'team-mutation',
    target: 'WP-8-TASK-BOARD',
    evidence: ['task revision and review reference'],
    refs: [['detail', '9e2ce9a330923369']],
  },
  {
    id: 'team.console.local-view',
    owner: 'team-console',
    disposition: 'direct',
    securityClass: 'renderer-local',
    target: 'WP-7-TEAM-CONSOLE',
    evidence: ['no server authority'],
    refs: [
      ['list', 'c40241bfedec76c5'],
      ['list', 'bfb04384019ff8a2'],
      ['list', '4fd19e07a723a058'],
      ['list', '7253b728045c5be7'],
      ['list', '495711757cb25a3d'],
      ['detail', '93356b94c86b9a31'],
      ['detail', '60524c5c20d1e755'],
      ['detail', '082021ccdae5c5a7'],
      ['detail', '5391ea0fc7047eb7'],
      ['create', '8ae85785caeac217'],
      ['create', 'bbd620637e74d07a'],
    ],
  },
  {
    id: 'team.console.desktop-editor',
    owner: 'team-console',
    disposition: 'desktop-only',
    securityClass: 'desktop-shell',
    target: 'ABSENT-BEFORE-HOSTED-MOUNT',
    evidence: ['hosted chunk import exclusion'],
    refs: [['detail', '4d51206ae5cc9e46']],
  },
  {
    id: 'team.lifecycle.draft.configure',
    owner: 'team-lifecycle',
    disposition: 'direct',
    securityClass: 'renderer-local-draft',
    target: 'WP-7-TEAM-LIFECYCLE',
    evidence: ['server revalidates accepted draft'],
    refs: [
      ['create', 'd5fe5d760046156d'],
      ['create', '6d8853fe55f75739'],
      ['create', 'fed55a4d724f8753'],
      ['create', '6eb6d60bd8a2b4f9'],
      ['create', '460a6a2c6167d111'],
      ['create', 'b595fc47dbad28f4'],
      ['create', 'cdb8b3b29e5bd5dc'],
      ['create', 'f57186dc2c15e899'],
      ['create', '2def27cf5dcb15c3'],
      ['create', '1a7ffd59f07eefa3'],
      ['create', '4f195bffd0ffd15b'],
      ['create', 'f021d7f085c99bfa'],
      ['create', 'd07a1c16e844146d'],
      ['create', 'f4d5123b4759ab0a'],
      ['create', 'efe1b616c01dac38'],
    ],
  },
  {
    id: 'provider.management.credentials.edit',
    owner: 'runtime-provider-management',
    disposition: 'direct',
    securityClass: 'secret-local-input',
    target: 'WP-4-PROVIDER-AVAILABILITY',
    evidence: ['credential never enters renderer evidence'],
    refs: [
      ['providers', '475f2078f99114db'],
      ['providers', '3816eb21807a0310'],
      ['providers', '9bfec2d3b0f3b701'],
      ['providers', 'c6ce0f9d97c1db56'],
      ['providers', '8e6244151887f85f'],
      ['providers', '0866a69dd465cea2'],
      ['providers', '32a0b93f9100520a'],
      ['providers', '90b5386bbc48f0ef'],
      ['providers', 'e61e6699ac805f3d'],
      ['providers', '2e96c75568c654f7'],
    ],
  },
  {
    id: 'provider.management.connect',
    owner: 'runtime-provider-management',
    disposition: 'direct',
    securityClass: 'provider-credential',
    target: 'WP-4-PROVIDER-AVAILABILITY',
    evidence: ['provider availability/auth result'],
    refs: [
      ['providers', '69d499064c5acd68'],
      ['providers', '6bc3452b02286516'],
      ['providers', '0762178282badb9e'],
      ['providers', '29c4895caee155e7'],
      ['providers', 'e05b1f72353d30ba'],
      ['providers', 'd168672245c63043'],
      ['providers', '3ad8822f863003a5'],
      ['providers', '1495ee29bd7c3e90'],
      ['providers', 'ac9b52278c788f42'],
    ],
  },
  {
    id: 'provider.management.connect.cancel',
    owner: 'runtime-provider-management',
    disposition: 'direct',
    securityClass: 'renderer-local',
    target: 'WP-4-PROVIDER-AVAILABILITY',
    evidence: ['no team lifecycle effect'],
    refs: [['providers', 'ad293317df8ded48']],
  },
  {
    id: 'provider.management.refresh',
    owner: 'runtime-provider-management',
    disposition: 'direct',
    securityClass: 'provider-read',
    target: 'WP-4-PROVIDER-AVAILABILITY',
    evidence: ['fresh availability projection'],
    refs: [
      ['providers', 'bcc0207e64dd80e9'],
      ['providers', '4db1c0b6fb7b9ffb'],
      ['providers', '08bc5dc7c332dd08'],
    ],
  },
  {
    id: 'provider.management.forget',
    owner: 'runtime-provider-management',
    disposition: 'direct',
    securityClass: 'destructive-provider-operator',
    target: 'WP-4-PROVIDER-AVAILABILITY',
    evidence: ['credential deletion outcome'],
    refs: [
      ['providers', '022abe36d0ffbc03'],
      ['providers', '2a7c06563fa1b014'],
    ],
  },
  {
    id: 'provider.management.provider.select',
    owner: 'runtime-provider-management',
    disposition: 'direct',
    securityClass: 'renderer-local',
    target: 'WP-4-PROVIDER-AVAILABILITY',
    evidence: ['keyboard/click equivalence'],
    refs: [
      ['providers', 'ac11e711a5ad0984'],
      ['providers', '70a068044f5b9d78'],
      ['providers', '884c2ef7b9d904ef'],
    ],
  },
  {
    id: 'provider.management.model.select',
    owner: 'runtime-provider-management',
    disposition: 'direct',
    securityClass: 'renderer-local',
    target: 'WP-4-PROVIDER-AVAILABILITY',
    evidence: ['keyboard/click equivalence'],
    refs: [['providers', 'ae63125fb8afa652']],
  },
  {
    id: 'provider.management.model.test',
    owner: 'runtime-provider-management',
    disposition: 'direct',
    securityClass: 'provider-execution-probe',
    target: 'WP-4-PROVIDER-AVAILABILITY',
    evidence: ['bounded test result'],
    refs: [
      ['providers', 'a64b1f2f3678ae66'],
      ['providers', 'b3f7d874e4b531e1'],
    ],
  },
  {
    id: 'provider.management.model.use-for-new-teams',
    owner: 'runtime-provider-management',
    disposition: 'direct',
    securityClass: 'provider-setting',
    target: 'WP-4-PROVIDER-AVAILABILITY',
    evidence: ['setting scope'],
    refs: [['providers', '4b4454a17e34e226']],
  },
  {
    id: 'provider.management.model.set-default',
    owner: 'runtime-provider-management',
    disposition: 'direct',
    securityClass: 'provider-setting',
    target: 'WP-4-PROVIDER-AVAILABILITY',
    evidence: ['setting scope'],
    refs: [['providers', '34e3adf63bf25705']],
  },
  {
    id: 'provider.management.model.page',
    owner: 'runtime-provider-management',
    disposition: 'direct',
    securityClass: 'provider-read',
    target: 'WP-4-PROVIDER-AVAILABILITY',
    evidence: ['bounded cursor and pagination'],
    refs: [['providers', 'c5c2275db5ceba29']],
  },
  {
    id: 'provider.management.directory.search',
    owner: 'runtime-provider-management',
    disposition: 'direct',
    securityClass: 'provider-read',
    target: 'WP-4-PROVIDER-AVAILABILITY',
    evidence: ['bounded query and pagination'],
    refs: [
      ['providers', '4e64864b4b16cd70'],
      ['providers', '6b69132fab97a1a0'],
      ['providers', 'b22672f4d62f3453'],
    ],
  },
  {
    id: 'provider.management.local-view',
    owner: 'runtime-provider-management',
    disposition: 'direct',
    securityClass: 'renderer-local',
    target: 'WP-4-PROVIDER-AVAILABILITY',
    evidence: ['no team lifecycle effect'],
    refs: [
      ['providers', '1cecb00a557a2370'],
      ['providers', '93445a71a9071b64'],
      ['providers', '6da470eb3cf1d2d1'],
      ['providers', '1a7ffd59f07eefa3'],
      ['providers', '17d88b307c87a317'],
      ['providers', '620ec57979b46e1d'],
      ['providers', 'e43bedc18cd77f93'],
      ['providers', '1e310b0bae09ff97'],
      ['providers', 'ea696b218060f2e5'],
      ['providers', 'abb468deaa0c78f4'],
      ['providers', '45ae2001fbe22fe4'],
      ['providers', '86ccffc56c2917aa'],
    ],
  },
];

export const absenceSeeds: Array<
  Omit<AbsenceRow, 'sourceRefs'> & {
    refs: Array<[keyof typeof REVIEWED_CONTROL_FILES, string]>;
  }
> = [
  {
    id: 'P0.W1.ABSENCE.dialog-state',
    reason: 'Dialog open/cancel state is local and creates no hosted command.',
    refs: [
      ['list', '6f151970571293da'],
      ['detail', '257597c3ce8bca4e'],
      ['detail', 'a30b08f387e731a0'],
      ['detail', '00e75ccb184739af'],
      ['detail', '85535c3fe2325671'],
      ['detail', '613400ca3d7039e8'],
      ['create', '089f3839d882cd3f'],
    ],
  },
  {
    id: 'P0.W1.ABSENCE.event-containment',
    reason: 'Event containment is not a semantic action.',
    refs: [
      ['providers', '49a1bb745fad7f34'],
      ['providers', '54f6c7a4459a5ffa'],
      ['providers', '60e136772eb5c4bc'],
      ['providers', '8b8e8db68dec5b0a'],
      ['providers', '66f02e5325663a12'],
    ],
  },
  {
    id: 'P0.W1.ABSENCE.disabled-wrapper',
    reason: 'A disabled presentation wrapper without a handler is not an action.',
    refs: [['providers', '726e1410bc9bb643']],
  },
];
