/**
 * Public source entry for the dependency-closed Owner anchor package.
 *
 * Keep this surface limited to process ownership. The package builder starts here, follows the
 * static dependency graph, and rejects any non-Node runtime dependency. Image admission and the
 * Owner's durable store implementation intentionally remain outside this library.
 */
export type {
  LegacyMemberKey,
  MemberId,
  RunId,
  TeamId,
  WorkspaceId,
} from '../../../../../shared/contracts/hosted';
export {
  parseLegacyMemberKey,
  parseMemberId,
  parseRunId,
  parseTeamId,
  parseWorkspaceId,
} from '../../../../../shared/contracts/hosted';
export type {
  AnchorChannelRef,
  AnchorIdentityRef,
  MainProcessIdentityRef,
  OwnedProcessRef,
  OwningProcessIdentityRef,
  ProcessBinaryBinding,
  ProcessControllerInstanceId,
  ProcessOwnerAttestation,
  ProcessOwnerBinding,
  ProcessOwnershipPlanRef,
  ProcessOwnershipScope,
  ProcessStopFence,
  ProcessSupervisionFailureReason,
  ProcessSupervisionProtocolVersion,
  ProcessWorkspaceBinding,
  SpawnNonce,
} from '../../../contracts/processSupervision';
export {
  isExactProcessOwnerAttestation,
  isExactProcessOwnershipPlanRef,
  isExactProcessOwnershipScope,
  isExactProcessWorkspaceBinding,
  parseAnchorChannelRef,
  parseAnchorIdentityRef,
  parseMainProcessIdentityRef,
  parseOwnedProcessRef,
  parseOwningProcessIdentityRef,
  parseProcessControllerInstanceId,
  parseProcessOwnerAttestation,
  parseProcessOwnerBinding,
  parseProcessOwnerBindingId,
  parseProcessSupervisionSha256,
  parseSpawnNonce,
  PROCESS_OWNER_ATTESTATION_VERSION,
  PROCESS_SUPERVISION_MAX_FRAME_BYTES,
  PROCESS_SUPERVISION_MAX_STATUS_FRAMES,
  PROCESS_SUPERVISION_MAX_STATUS_STREAM_BYTES,
  PROCESS_SUPERVISION_PROTOCOL_VERSION,
  ProcessSupervisionCancellationError,
  ProcessSupervisionProtocolError,
  ProcessSupervisionTimeoutError,
} from '../../../contracts/processSupervision';
export type {
  CompositeRuntimePlanHash,
  CredentialExposureSet,
  CredentialIsolation,
  ExecutionUnitId,
  HostedChildEnvironmentPolicy,
  HostedChildEnvironmentVariablePolicy,
  LaneId,
  ProcessExecutionUnit,
  RegisteredWorkspaceRuntimeBinding,
  ResolvedRuntimeBinaryPolicy,
  RuntimeBackendBindingId,
  RuntimeBinaryId,
  RuntimeExecutionBackendBinding,
  RuntimeExecutionBackendKind,
  RuntimePlanMemberBinding,
  RuntimeResourcePolicy,
  SecretClass,
  SecretRefId,
  SecretRefMetadata,
  Sha256Hash,
} from '../../../contracts/runtimePlan';
export {
  parseExecutionUnitId,
  parseLaneId,
  parseRuntimeBackendBindingId,
  parseRuntimeBinaryId,
  parseSecretClass,
  parseSecretRefId,
} from '../../../contracts/runtimePlan';
export type {
  ObserveProcessExecutionUnitRequest,
  ObserveProcessExecutionUnitResult,
  ProcessSupervisorPort,
  RecoverProcessExecutionUnitRequest,
  RecoverProcessExecutionUnitResult,
  ResolvedEnvironmentAuthorityRef,
  ResolvedExecutableAuthorityRef,
  ResolvedProcessArgvAuthority,
  ResolvedProcessEnvironmentAuthority,
  ResolvedProcessLaunchSpec,
  ResolvedProcessWorkdirAuthority,
  ResolvedWorkdirAuthorityRef,
  RuntimeCancellation,
  RuntimeCancellationId,
  RuntimePlanRef,
  StartProcessExecutionUnitRequest,
  StartProcessExecutionUnitResult,
  StopProcessExecutionUnitRequest,
  StopProcessExecutionUnitResult,
  SupervisedProcessRef,
  WorkspaceExecutionGrant,
  WorkspaceExecutionGrantId,
} from '../../../core/application/ports';
export type {
  LiveProcessChannelInspection,
  MonotonicClockPort,
  OwnedProcessControlPort,
  ProcessIdentityFactoryPort,
  ProcessOwnershipCompareAndSwapRequest,
  ProcessOwnershipCompareAndSwapResult,
  ProcessOwnershipLoadResult,
  ProcessOwnershipStoreContext,
  ProcessOwnershipStorePort,
  ProcessResidualEvidencePort,
  ProcessResidualEvidenceReadResult,
  ProcessSupervisionDeadline,
  ProcessSupervisionTimerPort,
  StopOwnedProcessEffectResult,
} from '../../../core/application/process-supervision/ports';
export {
  classifyBoundedProcessSupervisionFailure,
  createFailClosedCleanupCancellation,
  createFailClosedPersistenceContext,
  createProcessSupervisionDeadline,
  isCancellationRequested,
  isControllerInstanceExact,
  PROCESS_OWNERSHIP_CAS_RECONCILE_LIMIT,
  PROCESS_SUPERVISION_FAIL_CLOSED_PERSISTENCE_TIMEOUT_MS,
  remainingProcessSupervisionTime,
} from '../../../core/application/process-supervision/ports';
export type {
  CreateSpawnIntentValue,
  DrainedProcessOwnershipState,
  LiveProcessOwnershipState,
  OwnedProcessEofProof,
  OwnedProcessOwnershipState,
  ProcessDrainProof,
  ProcessOwnershipPhase,
  ProcessOwnershipReadyProof,
  ProcessOwnershipRecord,
  ProcessOwnershipState,
  SpawnIntent,
  SpawnIntentState,
  StoppingProcessOwnershipState,
  TerminalProcessOwnershipState,
  UnclassifiedProcessOwnershipState,
} from '../../../core/domain/process-supervision';
export {
  areOwnershipStatesEquivalent,
  areSpawnIntentBindingsExact,
  areSpawnIntentsExact,
  beginOwnedProcessStop,
  commitProcessOwnership,
  completeOwnedProcessStop,
  computeCanonicalArgvDigest,
  computeCanonicalPolicyDigest,
  createSpawnIntent,
  doesStateMatchStopFence,
  initializeProcessOwnershipState,
  markProcessOwnershipUnclassified,
  MAX_PROCESS_ARG_BYTES,
  MAX_PROCESS_ARGV_BYTES,
  MAX_PROCESS_ARGV_COUNT,
  PROCESS_OWNERSHIP_RECORD_VERSION,
  SPAWN_INTENT_VERSION,
  SpawnIntentValidationError,
  spawnNonceDigest,
} from '../../../core/domain/process-supervision';
export type {
  AnchorProcessSupervisorAdapterOptions,
  AnchorSpawnPort,
  AnchorSpawnRequest,
  AnchorSpawnResult,
  AttestedOwningProcessPort,
  OwningProcessInspection,
} from '../../adapters/output/process-supervision/AnchorProcessSupervisorAdapter';
export { AnchorProcessSupervisorAdapter } from '../../adapters/output/process-supervision/AnchorProcessSupervisorAdapter';
export type {
  MaterializedNodeAnchorLaunch,
  NodeAnchorLaunchAuthorityCatalog,
  NodeEnvironmentLaunchAuthority,
  NodeExecutableLaunchAuthority,
  NodeRegisteredWorkdirEvidence,
  NodeWorkdirLaunchAuthority,
} from './NodeAnchorLaunchMaterializer';
export { NodeAnchorLaunchMaterializer } from './NodeAnchorLaunchMaterializer';
export type {
  NodeAnchorProviderStdio,
  NodeAnchorSpawnerOptions,
  NodeAnchorSpawnProcess,
} from './NodeAnchorSpawner';
export {
  NODE_ANCHOR_MAX_LAUNCH_FRAME_BYTES,
  NODE_ANCHOR_PROVIDER_STDIO_CAPABILITY_HASH,
  NODE_ANCHOR_PROVIDER_STDIO_CAPABILITY_VERSION,
  NodeAnchorSpawner,
} from './NodeAnchorSpawner';
export { NodeAttestedOwningProcess } from './NodeAttestedOwningProcess';
